### ISSUE TITLE
Rave.validate() should not throw exception for unsupported models

### ISSUE THREAD

**Issue by allenchen1154** [uber-common/rave#40]
Library version: 1.0.1

Per the javadoc, "If the object is not supported, nothing will happen." I interpreted that as "this method will return normally if the provided object is not annotated `@Validated`. Instead, the method throws an `UnsupportedObjectException` for such models.

Personally, I think it makes more sense for unsupported models to behave the same as supported models that pass validation. In most cases, the current behavior would just lead to boilerplate like
```java
try {
    Rave.getInstance().validate(model);
} catch (UnsupportedObjectException e) {
    // do nothing
}
```

**Comment by naturalwarren** [comment]
> Per the javadoc, "If the object is not supported, nothing will happen." I interpreted that as "this method will return normally if the provided object is not annotated @Validated. Instead, the method throws an UnsupportedObjectException for such models.

I agree with your interpretation of the javadoc. We need to change this.

I believe the original idea behind throwing an `UnsupportedObjectException` was it provided a mechanism for consumers to take action when models that aren't opted into RAVE validation are validated. Some example actions include logging which models aren't validated (so they can be opted into validation) or dropping a model and returning null for it because it couldn't be validated.

At the cost of the additional boilerplate, I'd like to leave consumers the ability to take action when models that aren't opted into RAVE validation are validated. 

@behroozkhorashadi any additional thoughts here?

**Comment by behroozkhorashadi** [comment]
I think we should extend the Rave api to have a
Rave.validateIgnoreUnsupported() method (or something like that). Both
usages are useful to have.

**Comment by naturalwarren** [comment]
API added in 2.0.
